[package]
name = "bevy_tiles_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
bevy_ecs_tilemap = "0.14"
dungoxide = { path = "../../" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
